name = "StrataDoc"
defaultTargets = ["ddm", "langdef"]

[[require]]
name = "Strata"
path = "../.."

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"
rev = "nightly-testing"

[[lean_lib]]
name = "DDMDoc"

[[lean_lib]]
name = "LangDefDoc"

[[lean_exe]]
name = "ddm"
root = "DDMDocMain"

[[lean_exe]]
name = "langdef"
root = "LangDefDocMain"
